### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by dionisioC**
Hello

I was trying this project and I just updated some dependencies that don't break the project, if you are interested.

I am not able to update gatsby or react and I didnt found any issue related to those versions. It keeps in `Building development bundle` forever, verbose level is not helping me. I you have some idea of what could be happening I can try to update to latest gatsby/react version 

```gatsby develop --verbose
verbose set gatsby_log_level: "verbose"
verbose set gatsby_executing_command: "develop"
verbose loading local command from:
verbose running command: develop
success open and validate gatsby-configs - 0.021s
success load plugins - 0.468s
success onPreInit - 0.006s
success initialize cache - 0.007s
success copy gatsby files - 0.044s
success onPreBootstrap - 0.009s
success createSchemaCustomization - 0.009s
success source and transform nodes - 0.093s
success building schema - 0.215s

Created 501 pages of paginated content.
success createPages - 0.790s
warn Non-deterministic routing danger: Attempting to create page: "/404/", but page "/404" already exists
This could lead to non-deterministic routing behavior
success createPagesStatefully - 0.049s
success updating schema - 0.045s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.117s
success onPostBootstrap - 0.125s
info bootstrap finished - 3.686s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.200s
success write out requires - 0.025s
success run page queries - 0.252s - 505/505 2007.94/s
success write out requires - 0.003s
[styled-jsx] Loading plugin from path: styled-jsx-plugin-postcss
⠏ Building development bundle
^C^C^C^C^C^C^C^C
 ERROR 

(node:27132) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
not finished Building development bundle - 546.591s```

### CODE REVIEW

**Comment by dionisioC** [comment]
Not sure why the checks are failing. Seems to be the `gatsby build` command 

I get

```
View is initializing items according to page500.
success Building static HTML for pages - 1.601 s — 504/504 940.81 pages/second
info Done building in 17.409278808 sec
```

**Comment by baobabKoodaa** [comment]
Hey, thanks a lot for your offer to help with dependencies!

There is a bug in `styled-jsx-plugin-postcss` which causes it to get stuck with newer versions of Gatsby. It's not a crucial plugin for this project so you can remove the plugin (refactor anything that needs it). I [did this earlier with another starter](https://github.com/baobabKoodaa/gatsby-starter-photo-book/issues/4), but haven't done it with this one.

I'm personally really tired of updating dependencies and I would be super happy if you wanna do a PR with updated dependencies that don't break anything.

**Comment by dionisioC** [comment]
> Hey, thanks a lot for your offer to help with dependencies!
> 
> There is a bug in `styled-jsx-plugin-postcss` which causes it to get stuck with newer versions of Gatsby. It's not a crucial plugin for this project so you can remove the plugin (refactor anything that needs it). I [did this earlier with another starter](https://github.com/baobabKoodaa/gatsby-starter-photo-book/issues/4), but haven't done it with this one.
> 
> I'm personally really tired of updating dependencies and I would be super happy if you wanna do a PR with updated dependencies that don't break anything.

I removed the plugin and updated versions. After the version update some lint warnings came up, so I change the divs in trafficlight by buttons and give an aria-label and style so it looks the same as before

If I am correct the plugging is deprecated and it was just hot reloading the css, so nothing was refactored about the plugin.

What I am not sure is why the checks fail on gatsby build, if I run it, I got it correct

```
View is initializing items according to page500.
success Building static HTML for pages - 2.036s - 504/504 247.56/s
success onPostBuild - 0.002s
info Done building in 15.789294776 sec
```

If this get merged you can close the dependantbot PR as this has the `websocket-extensions` 0.1.4

**Comment by baobabKoodaa** [comment]
Looks like I merged this too hastily. Everything was working locally, but it was failing to build on Netlify (like you noted).

This is the error from Netlify logs:

```
6:13:05 PM: /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/init-starter.js:117
6:13:05 PM:   } catch {
6:13:05 PM:           ^
6:13:05 PM: SyntaxError: Unexpected token {
6:13:05 PM:     at createScript (vm.js:80:10)
6:13:05 PM:     at Object.runInThisContext (vm.js:139:10)
6:13:05 PM:     at Module._compile (module.js:617:28)
6:13:05 PM:     at Object.Module._extensions..js (module.js:664:10)
6:13:05 PM:     at Module.load (module.js:566:32)
6:13:05 PM:     at tryModuleLoad (module.js:506:12)
6:13:05 PM:     at Function.Module._load (module.js:498:3)
6:13:05 PM:     at Module.require (module.js:597:17)
6:13:05 PM:     at require (internal/module.js:11:18)
6:13:05 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/create-cli.js:28:20)
```

**Comment by dionisioC** [comment]
Never used Netlify

Could be a node version issue? I am using 

v12.18.1

Here they point the same issue

https://github.com/gatsbyjs/gatsby/issues/24389

**Comment by baobabKoodaa** [comment]
Hey, looks like I made a mistake when I tested locally. I accidentally tested an earlier version that didn't have your changes. Now that I'm testing the version with your changes, it looks like CSS is broken. If you run `gatsby develop` and navigate to the site, you will see errors in console. At least CSS hover effect doesn't work. This is unrelated to the Netlify error and seems to be caused by removing the PostCSS plugin. The code has nested CSS statements and there is no plugin to handle them.

I'm going to force push back to the earlier version, but I would be happy to merge a PR from you if you'd be willing to work this nested CSS issue (and any other errors that may come up).

**Comment by dionisioC** [comment]
You are right, I didn't notice that

I've been trying, but I think I am at the same point as you here:

https://github.com/baobabKoodaa/blog/issues/5

If I come up with a solution I will make a PR

Thanks for your time

**Pull request merged**
